version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8080:6000"

  logservice1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logservice1
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://db:27017/logs
    ports:
      - "34001:6000"

  logservice2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logservice2
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://db:27017/logs
    ports:
      - "34002:6000"

  logservice3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logservice3
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://db:27017/logs
    ports:
      - "34003:6000"

  db:
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - "27017:27017"
    command: mongod

volumes:
  mongodb:
  mongodb_config:

